const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('help')
    .setDescription('Show a guide for the Skira Ops bot commands.')
    .addStringOption(option =>
      option
        .setName('section')
        .setDescription('Which help section to show')
        .setRequired(false)
        .addChoices(
          { name: 'All', value: 'all' },
          { name: 'Trainee / MOS', value: 'trainee' },
          { name: 'HQ / Admin', value: 'hq' }
        )
    ),

  async execute(interaction) {
    await interaction.reply({
      content: buildHelpMessage(interaction.options.getString('section') || 'all'),
      ephemeral: true,
      allowedMentions: { users: [] },
    });
  },
};

function buildHelpMessage(section) {
  const traineeHelp = [
    '🪖 **TRAINEE & MOS COMMAND GUIDE**',
    '',
    'Use these commands in the trainee / MOS channel for trainee management and MOS qualification updates.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/approve**',
    'When a trainee is accepted within #recruitment-office, use this command to:',
    '• add the TR prefix to their nickname',
    '• give them the correct trainee roles',
    '• add them to the trainee spreadsheet',
    '• link their Discord ID to their trainee entry',
    '',
    'This is the main command for bringing a new trainee into the system properly.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/removetrainee**',
    'If a trainee has left, use this command to remove them from the trainee spreadsheet.',
    '',
    'How to use it:',
    '• If they are still in the Discord, just select their user',
    '• If they have already left the Discord, use either their Discord ID or SteamID64 instead',
    '',
    'The bot will remove the trainee entry using the linked record and, if possible, also remove the trainee roles / trainee nickname formatting.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/mos**',
    'Use this command to set a person’s MOS qualification rating to a specific level.',
    '',
    'What it does:',
    '• updates their MOS role in Discord',
    '• removes old MOS roles from that same category',
    '• updates the Ratings sheet automatically using their Discord ID',
    '',
    'This should be used whenever someone gains, loses, or changes an MOS qualification.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**Important notes**',
    '• /approve should always be used when first adding a trainee',
    '• /mos should only be used on ranked members, not trainees',
    '• if something looks incorrect in the sheets, let HQ know rather than guessing',
  ].join('\n');

  const hqHelp = [
    '📊 **HQ COMMAND GUIDE**',
    '',
    'Use these commands for rank changes, system checks, syncing, and sheet cleanup.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/setrank**',
    'Use this command to set a user’s rank.',
    '',
    'What it does:',
    '• updates their rank role in Discord',
    '• applies the correct breaker role',
    '• updates their nickname prefix',
    '• updates the Ratings sheet',
    '• if they were a trainee, removes them from the trainee sheet and moves them into the Ratings system properly',
    '',
    'Safety notes:',
    '• the command will stop if the member already has that rank',
    '• some higher-impact ranks require confirm = YES',
    '• if promoted from trainee, Infantry may be auto-assigned where appropriate',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/removeratings**',
    'Use this command to remove a person from the Ratings system.',
    '',
    'What it does:',
    '• removes their row from the Ratings sheet',
    '• removes their rank / MOS / related Skira roles where applicable',
    '• gives them the Community role',
    '• resets their nickname formatting where possible',
    '',
    'How to use it:',
    '• if they are still in the Discord, select their user',
    '• if not, use their Discord ID',
    '• this command requires confirm = YES',
    '',
    'Use this only when someone should no longer exist in the Ratings system and needs to be fully reset.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/syncall**',
    'Use this command to do a full safe sync of the system.',
    '',
    'What it does:',
    '• syncs ranked Discord members into the Ratings sheet',
    '• updates MOS values from current Discord roles',
    '• removes promoted people from the trainee sheet where a safe match exists',
    '• updates linked rows instead of relying on manual corrections',
    '',
    'Use this as the main repair / catch-up command when the bot, sheet, or roles look out of sync.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/auditmembers**',
    'Use this command to check for member linking issues.',
    '',
    'What it checks:',
    '• Ratings rows missing Discord IDs',
    '• trainee entries that still do not match correctly',
    '• ranked Discord members who are not properly linked to Ratings rows',
    '',
    'Use this when names, IDs, or promotions look wrong.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/auditmos**',
    'Use this command to check MOS values between Discord and the Ratings sheet.',
    '',
    'What it checks:',
    '• rows missing Discord IDs',
    '• rows where the Discord member cannot be found',
    '• MOS values in the sheet that do not match the person’s actual Discord MOS roles',
    '',
    'Use this when MOS ratings look wrong or outdated.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/auditratings**',
    'Use this command to audit the Ratings sheet for bad or suspicious entries.',
    '',
    'What it checks:',
    '• trainee rows that should not be in Ratings',
    '• Ex Skira rows that should not be in Ratings',
    '• missing or duplicate Discord IDs',
    '• rows that look unsafe or invalid',
    '',
    'Use this before doing manual cleanup.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**/cleanratings**',
    'Use this command to remove clearly invalid Ratings rows.',
    '',
    'Examples:',
    '• trainees accidentally left in Ratings',
    '• Ex Skira still showing in Ratings',
    '• rows linked to members who are no longer valid',
    '',
    'This is a cleanup command and should be used carefully, ideally after checking /auditratings first.',
    '',
    '━━━━━━━━━━━━━━━━━━━━━━━',
    '',
    '**Important notes**',
    '• /setrank is the main promotion command',
    '• /syncall is the main repair command',
    '• audit commands check for problems but do not directly change data',
    '• cleanup commands should be used carefully and only by people handling admin corrections',
  ].join('\n');

  if (section === 'trainee') {
    return traineeHelp;
  }

  if (section === 'hq') {
    return hqHelp;
  }

  return [traineeHelp, '', '━━━━━━━━━━━━━━━━━━━━━━━', '', hqHelp].join('\n');
}